version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 9999:80
    environment:
      WORDPRESS_DB_PASSWORD: dummynator
    volumes:
      - ./:/var/www/html/wp-content/plugins/dummynator

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: dummynator
